In [53]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

iris = load_iris()

In [54]:
le_score = cross_val_score(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000), iris.data, iris.target, cv=3)
le_score

array([0.98, 0.96, 0.98])

In [55]:
svm_score = cross_val_score(SVC(gamma='auto'), iris.data, iris.target, cv=3)
svm_score

array([0.98, 0.98, 0.96])

In [56]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)
rf_score

array([0.98, 0.92, 0.94])

In [57]:
dt_score = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
dt_score

array([0.98, 0.94, 1.  ])

In [58]:
print("Logistic Regression  : " + str(np.average(le_score)))
print("Support Vector Machine : " + str(np.average(svm_score)))
print("Random Forest : "  + str(np.average(rf_score)))
print("Decision Tree : " + str(np.average(dt_score)))

Logistic Regression  : 0.9733333333333333
Support Vector Machine : 0.9733333333333333
Random Forest : 0.9466666666666667
Decision Tree : 0.9733333333333333
