In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [47]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\arief\.conda\envs\Machine_learning_basic\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [48]:
svm = SVC(C=10, gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.39814814814814814

In [49]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

In [50]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [51]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [52]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [55]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [68]:
scores_l = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [69]:
scores_l

[0.9248747913188647, 0.9415692821368948, 0.9148580968280468]

In [70]:
score_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [71]:
score_rf

[0.9415692821368948, 0.9482470784641068, 0.9282136894824707]

In [72]:
from sklearn.model_selection import cross_val_score

In [76]:
cross_val_score(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [78]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [80]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.91666667, 0.90555556, 0.96657382, 0.96935933, 0.91643454])

In [81]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.85833333, 0.76666667, 0.88579387, 0.91922006, 0.82729805])

In [82]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target)

array([0.9       , 0.84722222, 0.9637883 , 0.94150418, 0.90529248])

In [84]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)

array([0.93055556, 0.91666667, 0.95264624, 0.96657382, 0.92200557])